### ISSUE TITLE
API change suggestion: pass platform(Application) only to methods that need it

### ISSUE THREAD

**Issue by abiskop** [evanshortiss/sns-mobile#11]
Currently, the interface strictly requires a platform to be passed into the constructor; however, only certain methods like `addUser` actually use it.
Suggesting to change the API in a way that the platform is only required on such methods, like e.g. [addUser](https://github.com/evanshortiss/sns-mobile/blob/c2b74df064fe1e45e175fab50d37dfe474ae0ddd/lib/interface.js#L114).

**Comment by evanshortiss** [comment]
I can see the rationale behind this, but to add it a few things would need to be taken into account:

1. If implemented, then the supplied _platformApplication_ String to functions would need to be of the correct type (Andorid/Kindle/iOS) or message formatting would encounter issues.
2. It could break backwards compatibility. We could work around it, but is it worth it?
3. Having separate objects for each platformApplication separates things out nicely I think, but I can be persuaded to change on this easily :)

**Comment by evanshortiss** [comment]
@abiskop will close this unless you'd _really_ like to see it added
