### ISSUE TITLE
Allow title for android

### ISSUE THREAD

**Issue by 0505gonzalez** [evanshortiss/sns-mobile#12]
Currently only messages can be sent, interface does not seem to allow titles.

**Comment by evanshortiss** [comment]
Hey @0505gonzalez,

Can you explain your issue a little further? 

If you want to include more than just a message String you can provide an Object containing extra parameters to use. As per the API docs:

**sendMessage(endpointArn, message, callback)**

Send a message to a user. The message parameter can be a String, or an Object with the formats below. The callback format is callback(err, messageId).

So you could do
```javascript
instance.sendMessage(endpointArn, {
  data: {
    title: 'Hello'
    message: 'World'
  }
}, callback)
```

**Comment by evanshortiss** [comment]
Hi @0505gonzalez, I'm going to close this. Please reopen it if you feel it's not solved.
