### ISSUE TITLE
license

### ISSUE THREAD

**Issue by alexklibisz** [evanshortiss/sns-mobile#13]
I don't see a license defined anywhere in the repo. Would you mink determining and adding a license?. Otherwise I cannot use it for a current project. Thank you

**Comment by alexklibisz** [comment]
Actually, spoke too soon. MIT license is defined on the npmjs.org page. Thanks

**Comment by evanshortiss** [comment]
Hey, 

As you've noticed the LICENCE is in the package.json. 

I'll also look to add a LICENCE file since this is a standard.
