### ISSUE TITLE
InvalidClientTokenId

### ISSUE THREAD

**Issue by cevatkerim** [evanshortiss/sns-mobile#14]
I'm getting this error:

 [InvalidClientTokenId: The security token included in the request is invalid.]
  message: 'The security token included in the request is invalid.',
  code: 'InvalidClientTokenId',

I checked the the policy and key details for the user and they are all fine. Not sure why it's giving me this.

Any ideas?

**Comment by evanshortiss** [comment]
@cevatkerim, sounds like your key/id are incorrect/invalid as per the error.

When you create an instance of SNS be sure to set these correctly:

```
accessKeyId: 'your_access_key_id',
secretAccessKey: 'your_secret_access_key'
```

Maybe try reversing them too? If that doesn't work then regenerate them and if it's still not working we'll need to do some digging.

**Comment by evanshortiss** [comment]
Closing this. @cevatkerim, let me know if you think it shouldn't be closed.
