### ISSUE TITLE
setAttributes signature in the readme is incorrect

### ISSUE THREAD

**Issue by contra** [evanshortiss/sns-mobile#15]
it says it returns the endpointArn as the second argument, but in fact it returns the attributes

**Comment by evanshortiss** [comment]
Hey contra, if you have pull request available I'm happy to merge, if not I'll try remember to update it.

**Comment by jokecamp** [comment]
Created a pull request here. https://github.com/evanshortiss/sns-mobile/pull/19

**Comment by evanshortiss** [comment]
Thanks @jokecamp
