### ISSUE TITLE
Batch sending

### ISSUE THREAD

**Issue by santimacia** [evanshortiss/sns-mobile#22]
How can I send a 1000 push different notification to a different users at the same time efficiently? For the same message I guess I can use the publish topic but if are different?

**Comment by evanshortiss** [comment]
You can use the topic features of SNS, or do something like this:

```js
function doSend (user, next) {
  // Assume user is a user entry from a db
  // Assume sns is a valid sns instance created earlier
  sns.sendMessage(user.endpointArn, 'Hi There!', next);
}

function done (err) {
  console.log('finsihed sending to all users');
}

async.each(userList, doSend, done);
```

@santimacia, since this does not appear to be an issue with the module I'll close this. Feel free to reopen if you think otherwise.
