### ISSUE TITLE
[Question] Adding a user even if already exists

### ISSUE THREAD

**Issue by alex-nishikawa** [evanshortiss/sns-mobile#23]
Would it be unwise to call addUser every time before sending a notification instead of having to keep track if the user was already created.

**Comment by evanshortiss** [comment]
@alex-nishikawa correct, you probably don't want to do this. It will add overhead, and I'm not sure if the same ID (Arn) will be returned each time meaning you'll build an enormous number of unnecessary Arns.

I've associated the Arn returned with a user account in a DB for this. It also includes the push token their device returned.
