### ISSUE TITLE
Unable to resolve module 

### ISSUE THREAD

**Issue by dbyilmaz** [evanshortiss/sns-mobile#29]
Hi ,
I am stuck with this error : UnableToResolve. Can you help me ? :)
I tried to 
1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
it is not solve my problem :/

 > error: bundling failed: "Unable to resolve module `util` from `/home/dby/react-native/sns/node_modules/sns-mobile/lib/interface.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

**Comment by dbyilmaz** [comment]
@evanshortiss  :+1:

**Comment by evanshortiss** [comment]
@dbyilmaz not sure I understand what the issue is. This module is designed to run on a backend server, not frontend yet you seem to be attempting to use it with React Native? 

Perhaps I've misunderstood, could you provide more detail on your setup?

**Comment by evanshortiss** [comment]
By the way, it appears to be a complaint about [this line](https://github.com/evanshortiss/sns-mobile/blob/master/lib/interface.js#L37) in the code. `util` is a core Node.js module, so it should always be found - hence why I think this is related to React Native and your specific setup.

**Comment by dbyilmaz** [comment]
this library use with nodejs backend server? I wanted to use with react native. I understand now this error situation.
