### ISSUE TITLE
Send VOIP Push to IOS

### ISSUE THREAD

**Issue by basitsattar** [evanshortiss/sns-mobile#31]
Hi, I am trying to send AWS push to IOS but getting error. Does this library supports sending voip push via Amazon SNS?

**Comment by evanshortiss** [comment]
@basitsattar I've not tested for this so I assume the answer is no. How did your testing go?

**Comment by basitsattar** [comment]
As far as I remember, I used aws own library due to lack of this functionality.

**Comment by evanshortiss** [comment]
@basitsattar what difference is there between the VOIP and regular push? From what I can find from Google it is more reliably delivered and the app will be launched in the background, but requires a different iOS certificate?

Other than those differences it seems as though the backend calls are the same (from what I can gather) so this module should work if you use the correct Application/Endpoint ARN.
