### ISSUE TITLE
How to send notification on IOS using GCM

### ISSUE THREAD

**Issue by saurabhschauhan** [evanshortiss/sns-mobile#32]
If someone has the idea how to send notification on IOS please share a demo link. 

I'm getting an error that "EndpointDisabled: Endpoint is disabled"

**Comment by evanshortiss** [comment]
@saurabhschauhan an example guide is [here](http://evanshortiss.com/development/mobile/2014/02/22/sns-push-notifications-using-nodejs.html)

It sounds like you might be targeting the incorrect APNS environment, for example APNS_SANDBOX vs. APNS or the device token is invalid.
