### ISSUE TITLE
Support for topics?

### ISSUE THREAD

**Issue by anthonywebb** [evanshortiss/sns-mobile#7]
Curious if you plan on adding support for subscribing and unsubscribing to topics?

**Comment by evanshortiss** [comment]
Hi Anthony,

It's not on my list of things to do as I haven't had a need to use them
yet. I'd be happy to have a collaborator add it so if you have work I'd be
happy to merge.

**Comment by abiskop** [comment]
Hey folks, I am currently working on this. When trying to run the tests, I realized that `SNS_ACCESS_KEY` and `SNS_KEY_ID` are actually interchanged:

https://github.com/evanshortiss/sns-mobile/blob/2d0dd8499c1996d064d85a687464b3bec311b1ee/test/index.js#L30

While at it, I'd change this; any objections?
Will open a PR during the day...
